//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphTheoryInWPF.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int MinNodeEllipsePadding {
            get {
                return ((int)(this["MinNodeEllipsePadding"]));
            }
            set {
                this["MinNodeEllipsePadding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int MaxNodeEllipsePadding {
            get {
                return ((int)(this["MaxNodeEllipsePadding"]));
            }
            set {
                this["MaxNodeEllipsePadding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseDynamicNodeEllipsePadding {
            get {
                return ((bool)(this["UseDynamicNodeEllipsePadding"]));
            }
            set {
                this["UseDynamicNodeEllipsePadding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ExtraPaddingPerConnection {
            get {
                return ((int)(this["ExtraPaddingPerConnection"]));
            }
            set {
                this["ExtraPaddingPerConnection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25, 55, 75")]
        public global::System.Drawing.Color NodeEllipseFillBrushColour {
            get {
                return ((global::System.Drawing.Color)(this["NodeEllipseFillBrushColour"]));
            }
            set {
                this["NodeEllipseFillBrushColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Magenta")]
        public global::System.Drawing.Color NodeEllipseStrokeBrushColour {
            get {
                return ((global::System.Drawing.Color)(this["NodeEllipseStrokeBrushColour"]));
            }
            set {
                this["NodeEllipseStrokeBrushColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19, 151, 91")]
        public global::System.Drawing.Color NodeEllipseTextBrushColour {
            get {
                return ((global::System.Drawing.Color)(this["NodeEllipseTextBrushColour"]));
            }
            set {
                this["NodeEllipseTextBrushColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color NodeConnectionNormalBrushColour {
            get {
                return ((global::System.Drawing.Color)(this["NodeConnectionNormalBrushColour"]));
            }
            set {
                this["NodeConnectionNormalBrushColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lime")]
        public global::System.Drawing.Color NodeConnectionPathBrushColour {
            get {
                return ((global::System.Drawing.Color)(this["NodeConnectionPathBrushColour"]));
            }
            set {
                this["NodeConnectionPathBrushColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllRoutesRadioButtonSelected {
            get {
                return ((bool)(this["AllRoutesRadioButtonSelected"]));
            }
            set {
                this["AllRoutesRadioButtonSelected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25, 55, 75")]
        public global::System.Drawing.Color CanvasBackgroundBrushColour {
            get {
                return ((global::System.Drawing.Color)(this["CanvasBackgroundBrushColour"]));
            }
            set {
                this["CanvasBackgroundBrushColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightGray")]
        public global::System.Drawing.Color CanvasNodeConnectionPreviewBrushColour {
            get {
                return ((global::System.Drawing.Color)(this["CanvasNodeConnectionPreviewBrushColour"]));
            }
            set {
                this["CanvasNodeConnectionPreviewBrushColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int FontSize {
            get {
                return ((int)(this["FontSize"]));
            }
            set {
                this["FontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int NodeEllipseStrokeThickness {
            get {
                return ((int)(this["NodeEllipseStrokeThickness"]));
            }
            set {
                this["NodeEllipseStrokeThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ConnectionStrokeThickness {
            get {
                return ((int)(this["ConnectionStrokeThickness"]));
            }
            set {
                this["ConnectionStrokeThickness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int ConnectionArrowHeadLength {
            get {
                return ((int)(this["ConnectionArrowHeadLength"]));
            }
            set {
                this["ConnectionArrowHeadLength"] = value;
            }
        }
    }
}
